services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
    networks:
      - moviehub-network

networks:
  moviehub-network:
    driver: bridge
